export const initialFormData = {
  user_id: "",
  var_email: "",
  var_mobile_no: "",
  var_first_name: "",
  var_second_name: "",
  var_name: "",
  last_name: "",
  var_alt_mobile: "",
  var_default_no: "",
  var_password: "",
  var_image: "",
  chr_gender: "",
  var_dob: "",
  chr_verify: "",
  var_device_token: "",
  refferal_code: "",
  created_date: "", 
  updated_date: "",
  is_active: false, // Boolean default
  role_id: "",
  user_type: "",
  var_country_code: "",
  job_title: "",
  company_name: "",
  company_email: "",
  company_website: "",
  country: "",
  category: "",
  product_type: "",
  currency: "",
  min_cost: "",
  gst_number: "",
  gst_certificate: "", 
  kyc_document_select: "",
  kyc_document_number: "",
  kyc_document: "",
  wash_care: "",
  neck_label: "",
  size_label: "",
  hang_tag: "",
  cart_count: 0, 
  
  

  // Address data
  address: [
    {
      _id: null,
      int_glcode: "",
      fk_user: "",
      var_house_no: "",
      var_app_name: "",
      var_landmark: "",
      var_country: "",
      var_state: "",
      var_city: "",
      var_country_code: "",
      var_pincode: "",
      chr_type: "",
      default_status: "",
      chr_publish: false,
      chr_delete: false,
      dt_createddate: "",
      dt_modifydate: "",
      var_ipaddress: "",
      billing_var_landmark: "",
      billing_var_country: "",
      billing_var_state: "",
      billing_var_city: "",
      billing_var_pincode: "",
      shipping_var_landmark: "",
      shipping_var_country: "",
      shipping_var_state: "",
      shipping_var_city: "",
      shipping_var_pincode: "",
      agreedSMS: "no", 
      agreedMail: "no", 
    },
  ],
};

// Default dropdown options
export const defaultDropdownOptions = {
  jobTitles: [],
  countries: [],
  categories: [],
  productTypes: [],
  currencies: [],
  kycDocumentTypes: [],
  states: [],
  cities: [],
  billingStates: [],
  billingCities: [],
  shippingStates: [],
  shippingCities: [],
};
